version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: twitch-downloader-backend
    ports:
      - "8080:8080"
    volumes:
      - ./downloads:/app/downloads
      - ./db:/app/db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: twitch-downloader-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
